Repository liquibase/liquibase-parent-pom, pull requests merged in 2024-08, with the labels that each got.

#181 Add aws profile
  pom.xml
Labels: TypeEnhancement

#182 Change version to 0.4.2
  pom.xml
Labels: skipReleaseNotes

#187 DAT-18315 Add liquibase.build.properties file with commit information to all extensions
  pom.xml
Labels: skipReleaseNotes, sdou
